MODULE kinds
USE ISO_FORTRAN_ENV, ONLY: INT32, INT64, REAL64
IMPLICIT NONE
PRIVATE
   INTEGER, PARAMETER, PUBLIC :: int_4 = INT32
   INTEGER, PARAMETER, PUBLIC :: int_8 = INT64
   INTEGER, PARAMETER, PUBLIC :: dp = REAL64

   REAL(kind=dp), PARAMETER, PUBLIC :: angstrom = 0.52917720859_dp
END MODULE kinds
